backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "noticia"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title EN", name: "title-en", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: Image, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Body EN", name: "body-en", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - folder: "src/noticias"
        label: "Page"
        name: "page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Title EN", name: "title-en", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Body EN", name: "body-en", widget: "markdown"}
      